[workspace]
members = [".", "kernel"]
exclude = ["AI-Module/broker", "AI-Module/telemetry-provider"]
default-members = ["."]
resolver = "2"

[package]
name = "tuwaiqos"
version = "0.5.0"
edition = "2021"
publish = false
build = "build.rs"

[lib]
path = "src/lib.rs"
crate-type = ["lib"]

[build-dependencies]
bootloader = { version = "0.11", default-features = false, features = ["bios"] }
llvm-tools = "0.1"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"